name: Build

on: [push, pull_request]

jobs:
  build_wheels_macos:
    name: Build wheels on ARM64 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]

    steps:
      - name: STEP 1. Checkout repository
        uses: actions/checkout@v3

      - name: STEP 2. Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: cp311-*
          CIBW_SKIP: "*-win32 *-musllinux_x86_64 *_i686"
          CIBW_BEFORE_BUILD_MACOS: >
            python -m pip install --upgrade pip setuptools wheel &&
            brew update && 
            brew install boost boost-python3
          CIBW_ARCHS_MACOS: arm64
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python -m pytest -v
        with:
          output-dir: wheelhouse

      - name: STEP 3. Upload wheel zip
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
