name: Build

on: [push, pull_request]

jobs:
  build_wheels_macos:
    name: Build wheels on macos-11
    runs-on: macos-11

    steps:
      - name: STEP 1. Checkout repository
        uses: actions/checkout@v3

      - name: STEP 2. Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel pytest

      - name: STEP 3. Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BEFORE_ALL_MACOS: "brew update && brew install boost boost-python3"
          CIBW_ARCHS_MACOS: arm64

      - name: STEP 4. Test wheel
        run: |
          pytest -v

      - name: STEP 5. Create wheel zip
        uses: vimtor/action-zip@v1.1
        with:
          files: stpyv8-${{ matrix.os }}-arm64-${{ matrix.python-version }}/
          recursive: false
          dest: stpyv8-${{ matrix.os }}-arm64-python-${{ matrix.python-version }}.zip

      - name: STEP 6. Upload wheel zip
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: stpyv8-${{ matrix.os }}-arm64-python-${{ matrix.python-version }}.zip
