name: MacOSX build workflow (debug)

on: [push, pull_request]

env:
  BOOST_VERSION: 1.83.0

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]
        python-version: ['3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel pytest

      - name: Platform configuration for macos-11
        if: ${{ matrix.os == 'macos-11' }}
        run:
          echo "PLATFORM_VERSION=11" >> $GITHUB_ENV

      - name: Platform configuration for macos-12
        if: ${{ matrix.os == 'macos-12' }}
        run:
          echo "PLATFORM_VERSION=12" >> $GITHUB_ENV

      - name: Platform configuration for macos-13
        if: ${{ matrix.os == 'macos-13' }}
        run:
          echo "PLATFORM_VERSION=13" >> $GITHUB_ENV

      - name: Install Boost
        uses: MarkusJx/install-boost@main
        id: install-boost
        with:
          link: static
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: ${{ env.PLATFORM_VERSION }}

      - name: Build wheel
        run: |
          ls ${{ env.BOOST_ROOT }}
          python setup.py v8
          sudo --preserve-env=STPYV8_DEBUG python setup.py sdist bdist_wheel -d stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug
          sudo --preserve-env=STPYV8_DEBUG python setup.py install
          sudo --preserve-env=STPYV8_DEBUG cp v8/out.gn/x64.release.sample/icudtl.dat stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug/icudtl.dat
        env:
          STPYV8_DEBUG: 1

      - name: Test wheel
        run: |
          pytest -v
        env:
          STPYV8_DEBUG: 1

      - name: Create wheel zip
        uses: vimtor/action-zip@v1.1
        with:
          files: stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug/
          recursive: false
          dest: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}-debug.zip

      - name: Upload wheel zip
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}-debug.zip
